name: C++ CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Or your preferred OS, e.g., windows-latest, macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Configure CMake
      run: cmake -B build # -B specifies the build directory

    - name: Build project
      run: cmake --build build # Build all targets in the build directory

    - name: Run CTest tests
      working-directory: build # Run tests from the build directory
      run: ctest --output-on-failure # Run CTest and show output for failed tests
